### ISSUE TITLE
is dimples installed successfully or not?

### ISSUE THREAD

**Issue by luckypoem** [waferbaby/dimples#1]
hi.

root@AR:~# gem install dimples
Fetching: dimples-1.9.1.gem (100%)
Successfully installed dimples-1.9.1
Parsing documentation for dimples-1.9.1
Installing ri documentation for dimples-1.9.1
Done installing documentation for dimples after 1 seconds
1 gem installed
root@AR:~# dimples --help
-bash: dimples: command not found
root@AR:~# dimples
-bash: dimples: command not found
root@AR:~#

i'm not sure is dimples installed successfully or not?
if not,how to install it successfully?

**Comment by waferbaby** [comment]
Hey there! Because this is really just a little hacky gem I threw together for my own needs, it doesn't yet have its own binary, and you need to wire it up via Ruby. Here's an example:

https://github.com/waferbaby/usesthis/blob/master/tasks/build

**Comment by luckypoem** [comment]
hello.

root@AR:/usr/local# git clone https://github.com/waferbaby/usesthis usesthis.com
root@AR:/usr/local# cd usesthis.com
root@AR:/usr/local/usesthis.com# cd tasks
root@AR:/usr/local/usesthis.com/tasks# bundle install
root@AR:/usr/local/usesthis.com/tasks# ./build (this command generates site dir in /usr/local/usesthis.com/)
root@AR:/usr/local/usesthis.com/tasks# cd ..
root@AR:/usr/local/usesthis.com# ls
Gemfile       LICENSE	 config  gear  links  posts   site   templates
Gemfile.lock  README.md  errors  lib   pages  public  tasks
root@AR:/usr/local/usesthis.com# cd site
root@AR:/usr/local/usesthis.com/site# ls
404.html  api	      community  images      robots.txt   stylesheets
about	  categories  feed.atom  interviews  sitemap.xml
root@AR:/usr/local/usesthis.com/site#

why there is no index.html in /usr/local/usesthis.com/site/ dir?

**Comment by waferbaby** [comment]
@luckypoem Weird quirk of the site - the `/interviews/` index page is also the main page (configured via the nginx config).

**Comment by luckypoem** [comment]
hello.

actually i copied the index.html from /usr/local/usesthis.com/site/interviews/ to /usr/local/usesthis.com/site/,then i pointed my domain to the site dir,and i setup a blog: http://ut.bright.biz.st/ ,but why the newest post: http://ut.bright.biz.st/interviews/john.doe/ doesn't appear in http://ut.bright.biz.st/ ? and the existent posts don't get aligned as per the publishing time's order.
how to fix the 2 issues?

**Comment by waferbaby** [comment]
Huh, weird! Have you got the code up somewhere so I can see what you're doing?

**Comment by luckypoem** [comment]
i didn't do more things.main part is third window above.
then  i copied the index.html from /usr/local/usesthis.com/site/interviews/ to /usr/local/usesthis.com/site/,then i pointed my domain to the site dir,and i setup a blog: http://ut.bright.biz.st/ 

my webserver is apache2.

**Comment by waferbaby** [comment]
Ah, it might be because I'm using nginx instead of apache, so that's what my config is for - would be interested to know if you do get it working with apache, though!

**Comment by luckypoem** [comment]
can u paste ur nginx config about usesthis.com?

**Comment by waferbaby** [comment]
https://github.com/waferbaby/usesthis/blob/master/config/nginx.conf

**Comment by luckypoem** [comment]
hi.

in another vps,it's nginx webserver, i setup http://ut2.bright.biz.st/ , as compared to http://ut.bright.biz.st/ ,the posts are randomly aligned,not aligned as per the publishing time's order at all.
how do u make ur posts aligned as per the publishing time's order in your site: https://usesthis.com/ ?

**Comment by waferbaby** [comment]
Oh, that's super weird! Are you naming the files with the dates? That's what it uses to sort the posts.

**Comment by waferbaby** [comment]
Did you have any luck? I've actually added a command-line tool to the latest version of Dimples, but no idea if that's useful.

**Comment by luckypoem** [comment]
where is the command-line tool usage guide?

**Comment by waferbaby** [comment]
I'm still working on the docs, but it's just `dimples build` in your site directory. More docs soon!

**Comment by waferbaby** [comment]
Docs updated! Closing this one out, but let me know if you run into issues.
